jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6'
      - uses: 'actions/setup-python@v6'
        with:
          python-version: '3.13'
      - name: 'Install Poetry'
        run: 'pipx install poetry'
      - run: 'poetry build'
      - uses: 'pypa/gh-action-pypi-publish@release/v1'
      - uses: 'softprops/action-gh-release@v2'
        with:
          files: 'dist/*'
name: 'Publish'
'on':
  push:
    tags:
      - 'v*'
permissions:
  contents: 'write'
  id-token: 'write'
